version: '3.5'
services:
  postgres:
    container_name: db_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: mario
      POSTGRES_PASSWORD: Sinclave1
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "5432:5432"
volumes:
  postgres-db:
    driver: local